name: Release

on:
  workflow_dispatch: # Only run when manually triggered

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          package-manager-cache: false

      - name: Enable Corepack
        run: corepack enable

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            **/.yarn/berry/cache
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run build & tests
        run: |
          cd tests
          yarn clean
          cd ..
          yarn clean
          yarn clean:all
          yarn build
          yarn test
          yarn update-samples
          yarn test:samples

      - name: Run release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release

      - name: Configure npm authentication
        run: |
          yarn config set npmRegistryServer "https://registry.npmjs.org"
          yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}

      - name: Publish workspaces to npm
        run: yarn workspaces foreach --all --no-private -v -p npm publish --tolerate-republish
