name: tests

on:
  pull_request:
    branches:
      - 'main'
      - 'master'
      - 'next'
permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x]
    steps:
      - name: Set git to use LF (instead of CRLF on Windows)
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable corepack
        run: corepack enable
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - name: formatting
        run: yarn format:check
      - name: unit tests
        run: yarn test:ci
      - name: tests install
        working-directory: ./tests
        run: yarn
      - name: tests generate
        working-directory: ./tests
        run: yarn generate
      - name: tests build
        working-directory: ./tests
        run: yarn build
      - name: test MCP server
        working-directory: ./tests
        run: yarn test:mcp-inspector
      - name: test MCP server with auth
        working-directory: ./tests
        run: yarn test:mcp-auth
